### ISSUE TITLE
Issue with installation documentation

### ISSUE THREAD

**Issue by ghost** [esa/pygmo#1]
Hi,
I have been mislead by the installation documentation on http://esa.github.io/pygmo/install.html
The documentation on https://github.com/esa/pagmo/wiki is well hidden. 

Is there any way to delete or link http://esa.github.io/pygmo/install.html to https://github.com/esa/pagmo/wiki so future users will not spend the same two weeks I have just spent trying to excecute instructions on http://esa.github.io/pygmo/install.html?

**Comment by darioizzo** [comment]
What exactly mislead you? And what did you find on the wiki that was helpful?

**Comment by ghost** [comment]
Hi Dario,

I read the installation instructions for Windows which on (
http://esa.github.io/pygmo/install.html) says you have to build everything
from source.
However using the wiki I could download an autoinstaller (
https://github.com/esa/pagmo/wiki/Installing-&-Upgrading). I have been
struggling to install PyGMO for 2 weeks now (Tried it on both Windows and
Linux) and after finding the autoinstaller, it took 2 mins.  (I am really
happy it is working - there aren't many Multi Objective Particle Swarm
Optimizers available)

The wiki has much more in depth instructions of how to build. (
https://github.com/esa/pagmo/wiki/Guide-to-Compilation-on-Linux and
https://github.com/esa/pagmo/wiki/Guide-to-Compilation-on-Windows-x86).
While the instructions on (http://esa.github.io/pygmo/install.html) are
helpful but not nearly as extensive as those on the wiki. I would have been
much better off without the installation instructions on PyGMO site, but
with a link to the wiki.

I thank you for the great software!

(Also I find it difficult to complain about something and not help with the fixing - Would be willing to help update the PyGMO page if I had access.)

**Comment by darioizzo** [comment]
You were lucky with the autoinstaller :) as that only works for python 3.4 and 64 bits. Otherwise you must compile it from source, which I know, its a hard thing to do. 

We are a very small community and the windows binaries are only made available for random versions and architectures according to uncontrollable events, that is why they are a bit hidden and not advertised  ...
