### ISSUE TITLE
How to know the number of individuals evaluated during evolution?

### ISSUE THREAD

**Issue by Greenwicher** [esa/pygmo#3]
Hi,

Thanks for your wonderful and fast package for the multi-objective optimization. It's quite powerful. 

Currently, I'm developing a random search method to solve multi-objective optimization and I want to compare different algorithms by plotting the number of individuals evaluated v.s. hypervolume as figure below. But I don't know how to get the number of individuals evaluated after each evolution. 

Figure: [https://www.dropbox.com/s/a7y23whh81nzwz2/algo-comparison.png?dl=0](url)

For example, consider the script below

```
from PyGMO import *
prob =  problem.zdt(3,2)
alg =  algorithm.nsga_II(gen = n_gen)
pop =  population(prob, n_population)
ref_point = (10,) * 2
for i in range(n_trials):
    pop = alg.evolve(pop)
    print('Iteration %d HV = %.5f' % (i, PyGMO.hypervolume(pop).compute(ref_point)))
```

Can I say the number of individuals evaluated after iteration i is n_gen*n_population*(i+1)? Is it true for other algorithms (say NSPSO, SPEA2..)?

I'd appreciate it very much if you can help me with this issue. 

Thanks,
Weizhi

**Comment by darioizzo** [comment]
There is a counter in problem .. I think it's called f_evals, did you try that?

**Comment by Greenwicher** [comment]
Hi Darioizzo,

Thanks for your quick reply. I guess it should be pop.problem.fevals, but I didn't see any documentation on this api. May I ask if this is equivalent to the number of individuals evaluated for deterministic case?  

Furthermore, are there any methods letting the algorithm terminate when the problem evaluation exceeds some thresholds?

Thanks,
Weizhi

**Comment by darioizzo** [comment]
fevals counts exactly how many time the obj fun is called. Depending on the
algo this will have some relation to the number of individuals in the
population and the generations evolved.

The stopping criteria for the algorithms are all base don the number of
generations evolved, not on fevals. As said these are related but you need
to figure out how many generation will use how many fevals.

Dario

**Comment by Greenwicher** [comment]
Copy that, I think the fevals is just what I need. For the deterministic case, I think there is no need to evaluate the same individual again for most algorithms. Thanks again!

Thanks,
Weizhi
