### ISSUE TITLE
Meta-problems for Discrete Optimization (except Integer Optimization)

### ISSUE THREAD

**Issue by Greenwicher** [esa/pygmo#4]
Hi,

I have checked the user documentation about the supported optimization problem types (see [here](http://esa.github.io/pygmo/documentation/problems.html)). It seems that the only supported discrete optimization is integer optimization. However, may I ask if there are any meta-problems methods to support the discrete problems except integer optimization.

Take ZDT1 as example, the variable bound is [0, 1], and we discretize it into 101 points (i.e. [0, 0.01, 0.02, 0.03, ..., 0.99, 1.00]). Then how do we modify the ZDT1 problems based on meta-problems or any possible approaches? Also, suppose we can discretize the ZDT1 problem, will NSGA2, SPEA2, SMSEMOA and IHS solve this kind of problems?

Thanks in advance! Have a nice day!

Best,
Weizhi

**Comment by darioizzo** [comment]
I am not sure I get your question, but ...

1) use gitter to post questions as there is a larger community there: https://gitter.im/esa/pagmo
2) ZDT1 is continuous, why would you want to discretize it? Was that just an example?
3) As far as I understand all discrete problems can be reduced to integer optimization problems. SO We never though to offer a different support but that to integer optimization. Can you give an example of a case where this is not true? That is, a discrete problem that is not ultimately an integer optimization problem?

Dario

**Comment by Greenwicher** [comment]
Hi Dario,

Thanks for your prompt response and the wonderful gitter platform. 

Firstly, sorry about the confusion. As you said, the ZDT1 is continuous and the reason why I want to discretize it is I'm doing a research related to multi-objective discrete optimization via simulation. In order to keep the consistency, I'm just wondering whether the ZDTs test problems provided by PyGMO can support the discrete domain. 

Secondly,  I agree that we can map all the discrete feasible solutions to some integers (say 0.00->0, 0.01->1, ...., 0.99->99, 1.00->100) such that perhaps most of the discrete optimization can be reduced to integer optimization. In this case, is that possible for me to use this mapping to transform the original ZDTs to the desired discrete optimization problems?

Thanks,
Weizhi

**Comment by darioizzo** [comment]
We do not have that coded already as a meta-problem, you would have to write it yourself.... but it looks like relatively straight forward and within PaGMO capabilities.

**Comment by Greenwicher** [comment]
Thanks a lot anyway. Let me try to figure it out. I believe it might not be difficult to propose a new discrete version of ZDTs. Regarding the generation of new points for the algorithms (say NSGA2), I might transform the solution into the required format when evaluating the objective values.
